### ISSUE TITLE
大佬，播放视频报错了   java.io.IOException: DummyDataSource cannot be opened

### ISSUE THREAD

**Issue by keternity** [iielse/imageviewer#122]
大佬，打开demo，播放视频报错了，能帮忙看看么 ，膜拜！！！

2021-07-04 19:18:35.514 23635-24325/com.xinbo.suibo E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:216)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: java.io.IOException: DummyDataSource cannot be opened
        at com.google.android.exoplayer2.upstream.DummyDataSource.open(DummyDataSource.java:39)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:774)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:587)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1016)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)
2021-07-04 19:18:35.539 23635-23635/com.xinbo.suibo E/EventLogger: playerFailed [eventTime=3.09, mediaPos=0.00, window=0, period=0
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:216)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: java.io.IOException: DummyDataSource cannot be opened
        at com.google.android.exoplayer2.upstream.DummyDataSource.open(DummyDataSource.java:39)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:774)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:587)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1016)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)
    ]

**Comment by keternity** [comment]
![image](https://user-images.githubusercontent.com/16664891/124383204-bbc4b700-dcfd-11eb-8104-279fad70b656.png)

**Comment by keternity** [comment]
ExoSourceManager.java 升级了下就好了。。。。不知道是不是我的问题
