### ISSUE TITLE
播放视频报错是什么问题？

### ISSUE THREAD

**Issue by Krystal1220** [iielse/imageviewer#123]
播放视频报错是什么问题？
E/EventLogger: internalError [eventTime=3.02, mediaPos=0.00, window=0, period=0, loadError
      java.io.IOException: DummyDataSource cannot be opened
        at com.google.android.exoplayer2.upstream.DummyDataSource.open(DummyDataSource.java:39)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:774)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:587)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1016)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
    ]

E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:233)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.io.IOException: DummyDataSource cannot be opened
        at com.google.android.exoplayer2.upstream.DummyDataSource.open(DummyDataSource.java:39)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:774)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:587)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1016)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)

**Comment by iielse** [comment]
SimpleExoPlayer.setMediaSources 报错了.
上个版本给 ExoVideoView 开了2个方法  
fun resume(provider: MediaSourceProvider? = null)
fun player(provider: MediaSourceProvider? = null)
demo TestActivity有使用代码， 可以先替换成自己的MediaDateSource
