### ISSUE TITLE
多张(有四十多张，每张大概1M)，爆炸了

### ISSUE THREAD

**Issue by LJPdream** [iielse/ImageViewer#58]
E/CrashReport: java.lang.RuntimeException: Canvas: trying to draw too large(144000000bytes) bitmap.
        at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:229)
        at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:97)
        at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:529)
        at android.widget.ImageView.onDraw(ImageView.java:1371)
        at android.view.View.draw(View.java:19145)
        at android.view.View.updateDisplayListIfDirty(View.java:18095)
        at android.view.View.draw(View.java:18873)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4216)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4002)
        at android.view.View.updateDisplayListIfDirty(View.java:18086)
        at android.view.View.draw(View.java:18873)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4216)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4002)
        at android.view.View.draw(View.java:19148)
        at android.support.v4.view.ViewPager.draw(ViewPager.java:2420)
        at android.view.View.updateDisplayListIfDirty(View.java:18095)
        at android.view.View.draw(View.java:18873)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4216)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4002)
        at android.view.View.draw(View.java:19148)
        at android.view.View.updateDisplayListIfDirty(View.java:18095)
        at android.view.View.draw(View.java:18873)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4216)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4002)
        at android.view.View.draw(View.java:19148)
        at com.android.internal.policy.DecorView.draw(DecorView.java:788)
        at android.view.View.updateDisplayListIfDirty(View.java:18095)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:652)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:658)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:766)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3045)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2840)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2393)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1426)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6873)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1026)
        at android.view.Choreographer.doCallbacks(Choreographer.java:838)
        at android.view.Choreographer.doFrame(Choreographer.java:769)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1012)
        at android.os.Handler.handleCallback(Handler.java:792)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6701)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)

**Comment by iielse** [comment]
对超大图的加载方案同 https://github.com/iielse/ImageViewer/issues/27
